<?php
/**
 * Author: xuqingfeng <js-xqf@hotmail.com>
 * Date: 15/4/3
 */
?>

<div class="container">
    <?php
    $homeActive = "";
    $questionsActive = "";
    if ('home' == $tab) {
        $homeActive = "active-tab";
    }
    if ('qna' == $tab) {
        $questionsActive = "active-tab";
    }
    ?>
    <a href="/home" class="tab <?php echo $homeActive; ?>">Home</a>
    <a href="/qna" class="tab <?php echo $questionsActive; ?>">Questions</a>
</div>

<div class="container">
    <?php
    if ('home' == $tab):
        ?>
        <a href="/news/new" class="new-button u-pull-right">New</a>
    <?php
    endif;
    ?>
    <?php
    if ('qna' == $tab):
        ?>
        <a href="/question/new" class="new-button u-pull-right">Ask</a>
    <?php
    endif;
    ?>
</div>
<div class="container">
    <?php
    $date = date('Ymd');
    if ('home' == $tab):
        $news = new News();
        $latestNews = $news->getLatestNews($date);
        foreach ($latestNews as $n):
            ?>
            <div class="row split">
                <div class="center-text one columns desktop-only">
                    <div data-icon="ei-chevron-up" data-size="s"></div>
                    <div><?php echo($n->voteUp - $n->voteDown);?></div>
                </div>
                <div class="eleven columns">
                    <div><a href="/n/<?php echo $n->date . '/' . $n->time;?>"
                            class="main-title"><?php echo $n->title;?></a>

                        <div class="u-pull-right">
                            <a href="<?php echo $n->link;?>" target="_blank"><?php echo $n->showLink;?></a>
                        </div>
                    </div>
                    <div class="main-description"><a
                            href="/m/<?php echo $n->publisher;?>"><?php echo $n->publisher;?></a>
                        • <?php echo date('H:i', strtotime($n->createAt));?> • <?php echo $n->comments;?> comments
                    </div>
                </div>
            </div>
        <?php
        endforeach;
    endif;
    ?>

    <?php
    if ('qna' == $tab):
        $question = new Question();
        $latestQuestions = $question->getLatestQuestions($date);
        foreach ($latestQuestions as $q):
            ?>
            <div class="row split">
                <div class="center-text one column desktop-only">
                    <div data-icon="ei-chevron-up" data-size="s"></div>
                    <div><?php echo $q->voteUp - $q->voteDown;?></div>
                </div>
                <div class="eleven columns">
                    <div>
                        <a href="/q/<?php echo $q->date . '/' . $q->time;?>"
                           class="main-title"><?php echo $q->title;?></a>
                    </div>
                    <div class="main-description"><a
                            href="/m/<?php echo $q->publisher;?>"><?php echo $q->publisher;?></a>
                        • <?php echo date('H:i', strtotime($q->createAt));?> • <?php echo $q->comments;?> comments
                    </div>
                </div>
            </div>
        <?php
        endforeach;
    endif;
    ?>

</div>

<div class="container">
    <br/>
    <a href="<?php if ('home' == $tab) {
        echo "/news/list";
    } else {
        echo "/question/list";
    } ?>" class="u-pull-right">More</a>
</div>