<?php
/**
 * Author: xuqingfeng <js-xqf@hotmail.com>
 * Date: 15/4/16
 */
?>

<div class="container">
    <div class="row">
        <div class="center-text two columns vote">
            <div data-icon="ei-chevron-up" data-size="m"></div>
            <div data-icon="ei-chevron-down" data-size="m"></div>
            <div><?php echo ($news->voteUp - $news->voteDown); ?></div>
        </div>
        <div class="ten columns">
            <div>
                <div class="detail-title">
                    <?php echo $news->title; ?>
                </div>
                <a href="<?php echo $news->link; ?>" target="_blank"><?php echo $news->showLink; ?></a>

                <div class="split"></div>
                <?php echo $news->parsedBody; ?>
                <br/>
                <?php echo $news->publisher . ' • ' . $news->createAt; ?>
            </div>
        </div>
    </div>
    <!-- get replies   -->
    <hr/>
    <div class="row">
        <?php
        //        var_dump($replies);
        if (isset($replies)):
            $user = new User();
            foreach ($replies as $reply):
                ?>
                <?php
                $publisher = $reply->publisher;
                $u = $user->getUserByName($publisher);
                ?>
                <div class="row">
                    <div class="one column">
                        <img src="<?php echo $u->avatarUrl;?>" alt="" class="profile-img"/>
                    </div>
                    <div class="ten columns">
                        <?php echo $reply->parsedBody;?>
                        <br/>
                        <?php echo $reply->publisher . ' • ' . $reply->createAt; ?>
                    </div>
                    <div class="one column">
                        <span>#1</span>
                    </div>
                </div>
            <?php
            endforeach;
        endif;
        ?>
    </div>

    <br/>
    <?php
    $auth = $this->session->get('auth');
    if ($auth):
        $name = $auth['name'];
        $user = new User();
        $u = $user->getUserByName($name);
        ?>
        <div class="row">
            <!--            <div class="two columns" align="center">-->
            <!--                <img src="--><?php //echo $u->avatarUrl;
            ?><!--" class="profile-img"/>-->
            <!--            </div>-->
            <div class="ten columns u-pull-right">
                <form action="" method="post">
                    <input type="hidden" name="<?php echo $this->security->getTokenKey();?>"
                           value="<?php echo $this->security->getToken();?>"/>
                    <input type="hidden" name="targetType" value="news"/>
                    <textarea name="reply" cols="30" rows="10" class="u-full-width"></textarea>
                    <input type="submit" class="button-primary u-pull-right" value="Reply"/>
                </form>
            </div>
        </div>
    <?php
    endif;
    ?>

</div>