<?php
/**
 * Author: xuqingfeng <js-xqf@hotmail.com>
 * Date: 15/4/27
 */

?>
<br/>
<div class="container">
    <div class="row">
        <div class="one column">
            <img src="<?php echo $user->avatarUrl; ?>" alt="" class="profile-img"/>
        </div>
        <div class="eleven columns">
            Joined At : <?php echo date('Y-m-d', strtotime( $user->createAt ));?> Reputation : <?php echo $user->reputation;?>
            <br/>
            <?php echo $user->updateAt;?>
        </div>
    </div>
</div>
