<?php
/**
 * Author: xuqingfeng <js-xqf@hotmail.com>
 * Date: 15/5/15
 */
?>

<br/>
<div class="container">
    <form action="" method="post">
        <input type="text" name="name" placeholder="name"/>
        <input type="text" name="showName" placeholder="showName"/>
        <input type="text" name="avatarUrl" placeholder="avatarUrl"/>
        <input type="text" name="email" placeholder="email"/>
        <input type="text" name="role" placeholder="role"/>
        <input type="text" name="reputation" placeholder="reputation"/>
        <button type="submit">create</button>
    </form>
</div>