<?php
/**
 * Author: xuqingfeng <js-xqf@hotmail.com>
 * Date: 15/4/3
 */
?>

<!doctype html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->config->environment->title; ?></title>
    <!-- smart version -->
    <link rel="icon" href="/dev/img/N@2x.png?v=2" sizes="64x64"/>
    <!-- change position TODO  -->
    <?php $this->assets->outputCss(); ?>
    <?php $this->assets->outputJs(); ?>
</head>
<body>

<div class="container">
    <nav class="navbar">
        <div class="container">
            <ul class="navbar-list">
                <li class="navbar-item">
                    <a href="<?php echo $this->config->environment->homepage; ?>" class="navbar-link">News Biu</a>
                </li>
                <!--                <li class="navbar-item">-->
                <!--                    <div data-icon="ei-bell" data-size="s"></div>-->
                <!--                </li>-->
                <li class="avatar">
                    <?php
                    $auth = $this->session->get('auth');
                    if (isset($auth)):
                        $name = $auth['name'];
                        $user = new User();
                        $u = $user->getUserByName($name);
                        ?>
                        <!--                        <div class="u-pull-right">-->
                        <!--                            <div data-icon="ei-bell" data-size="s"></div>-->
                        <!--                        </div>-->
                        <div class="u-pull-right">
                            <a href="/m/<?php echo $name;?>"><img src="<?php echo $u->avatarUrl;?>" class="profile-img"/></a>
                        </div>

                    <?php
                    endif;
                    ?>
                    <?php
                    if (!isset($auth)):
                        ?>
                        <a href="/member/login">
                            <div data-icon="ei-sc-github" data-size="m" class="login-button"></div>
                        </a>

                    <?php
                    endif;
                    ?>

                </li>
            </ul>
        </div>
    </nav>

    <?php echo $this->getContent(); ?>

    <!--    no whitespace !!-->
    <div>
        <div class="color-one-divider"></div><div class="color-two-divider"></div><div class="color-three-divider"></div><div class="color-four-divider"></div>
    </div>

    <div class="container">
        <div class="u-pull-left"><a href="/humans.txt">About</a></div>
        <div class="u-pull-right"><a href="https://github.com/xuqingfeng/NewsBiu/issues" target="_blank">Report an
                issue</a></div>
    </div>

</div>

<script>
    (function () {

        var auth =<?php if(isset($auth)){echo "true";}else{echo "false";}?>;

        $('a.new-button').on('click', function (evt) {
            evt.preventDefault();
            var href = $(this).attr('href');

            if (!auth) {
                swal({
                    title: "Please login first !",
                    text: "Github account only.",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "OK",
                    closeOnConfirm: true
                }, function (isConfirm) {
//                    swal("Deleted!", "Your imaginary file has been deleted.", "success");
                    if(isConfirm){
                        console.log('OK');
                        window.location.href = "/member/login";
                    }else{
                        console.log('Cancel');
                    }
                });
            }else{
                window.location.href = href;
            }
        });

    })();
</script>
</body>
</html>