<?php
/**
 * Author: xuqingfeng <js-xqf@hotmail.com>
 * Date: 15/4/3
 */
?>

<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8"/>
<!--    <meta name="description" content=""/>-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="google-site-verification" content="4WjS37nRVmtfN3FAIJ17XnaUPIwQcr3q0CQGd2oJlrQ" />
    <title><?php if(isset($seoTitle)){ echo $seoTitle." - News Biu";}else{echo $this->config->environment->title;} ?></title>
    <link rel="icon" href="/<?php echo STATE;?>/img/N@2x.png" sizes="64x64"/>
    <?php $this->assets->outputCss(); ?>
    <?php $this->assets->outputJs('js-evil-icons'); ?>
</head>
<body>

<div class="container">
    <nav class="navbar">
        <div class="container">
            <ul class="navbar-list">
                <li class="navbar-item">
                    <a href="/" class="navbar-link">News Biu</a>
                </li>
                <li class="avatar">
                    <?php
                    $auth = $this->session->get('auth');
                    if (isset($auth)):
                        $name = $auth['name'];
                        $user = new User();
                        $u = $user->getUserByName($name);
                        ?>
                        <div class="u-pull-right">
                            <a href="/m/<?php echo $name;?>"><img src="<?php echo $u->avatarUrl;?>"
                                                                  class="profile-img"/></a>
                            <a href="/settings">
                                <div data-icon="ei-gear" data-size="m"></div>
                            </a>
                            <a href="/notifications">
                                <div data-icon="ei-bell" data-size="m" class="<?php if(0===$u->notified){echo 'notification-active';}?>"></div>
                            </a>
                        </div>

                    <?php
                    endif;
                    ?>
                    <?php
                    if (!isset($auth)):
                        ?>
                        <a href="/member/login">
                            <div data-icon="ei-sc-github" data-size="m" class="login-button"></div>
                        </a>

                    <?php
                    endif;
                    ?>

                </li>
            </ul>
        </div>
    </nav>

    <?php echo $this->getContent(); ?>

    <!--    no whitespace !!-->
    <div>
        <div class="color-one-divider"></div><div class="color-two-divider"></div><div class="color-three-divider"></div><div class="color-four-divider"></div>
    </div>

    <div class="container">
        <div class="u-pull-left"><a href="/humans.txt">About</a></div>
        <div class="u-pull-right"><a href="https://github.com/xuqingfeng/newsbiu.org/issues" target="_blank">Report an issue</a></div>
    </div>

</div>

<?php $this->assets->outputJs(); ?>
<script>
    (function () {

        var auth = <?php if(isset($auth)){echo "true";}else{echo "false";}?>;
        var isPublisher = <?php if(isset($isPublisher) && $isPublisher){echo "true";}else{echo "false";}?>;
        var voteUrl = "/member/vote";
        // homepage
        $('a.new-button').on('click', function (evt) {
            evt.preventDefault();
            var href = $(this).attr('href');

            if (checkAuth()) {
                window.location.href = href;
            }
        });

        var date = "<?php if(isset($date)){echo $date;}else{echo 'null';}?>";
        var time = "<?php if(isset($time)){echo $time;}else{echo 'null';}?>";
        var type = "<?php if(isset($type)){echo $type;}else{echo 'null';}?>";
        var targetId = date + '/' + time;
        function checkVoteQualification(){
            if(date != null && time != null && type != null){
                return true;
            }
            return false;
        }

        // detail page
        $('.vote').on('click', '.icon--ei-chevron-up', function () {
            if (checkAuth() && !isPublisher) {
                if ($(this).hasClass('vote-active')) {
                    removeVoteActive();
                    // cancel vote && get vote count
                    if (checkVoteQualification()) {
                        vote(targetId, type, 0, $(this));
                    }
                } else {
                    removeVoteActive();
                    // vote && get vote count
                    if (checkVoteQualification()) {
                        vote(targetId, type, 1, $(this));
                    }
                }

            }
        });
        $('.vote').on('click', '.icon--ei-chevron-down', function () {
            if (checkAuth() && !isPublisher) {
                if($(this).hasClass('vote-active')){
                    removeVoteActive();
                    if(checkVoteQualification()){
                        vote(targetId, type, 0, $(this));
                    }
                }else{
                    removeVoteActive();
                    if(checkVoteQualification()){
                        vote(targetId, type, -1, $(this));
                    }
                }
            }
        });
        function removeVoteActive(){
            $('.vote').find('div.icon').removeClass('vote-active');
        }

        // actionValue: 1-voteUp 0-cancel -1-voteDown
        function vote(targetId, targetType, voteValue, target) {
            console.log('vote:'+targetId+'-'+targetType+'-'+voteValue);
            $.ajax({
                url: voteUrl,
                type: 'POST',
                data: {targetId: targetId, targetType: targetType, voteValue: voteValue},
                success: function (data) {
                    var msg = JSON.parse(data);
                    console.log(msg);
                    if(msg['success']){
                        if(1===voteValue || -1===voteValue){
                            target.addClass('vote-active');
                        }else if(0===voteValue){
                            target.removeClass('vote-active');
                        }
                        $('#vote-count').text(msg['voteCount']);
                    }else{
                        console.log(msg);
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log(textStatus+'-'+errorThrown);
                },
                complete: function () {
                    console.log('complete');
                }
            });
        }

        function checkAuth() {
            if (!auth) {
                swal({
                    title: "Please Login !",
                    text: "Github account only.",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "OK",
                    closeOnConfirm: true
                }, function (isConfirm) {
                    if (isConfirm) {
                        window.location.href = "/member/login";
                    } else {
                        return false;
                    }
                });
            } else {
                return true;
            }
        }



    })();
</script>
</body>
</html>