<?php
/**
 * Author: xuqingfeng <js-xqf@hotmail.com>
 * Date: 15/4/3
 */
?>

<!doctype html>
<html>
<head>
    <meta charset="UTF-8"/>
    <meta name="description" content=""/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->config->environment->title; ?></title>
    <!-- smart -->
    <link rel="icon" href="/dev/img/N@2x.png?v=2" sizes="64x64"/>
    <?php $this->assets->outputCss(); ?>
    <?php $this->assets->outputJs(); ?>
    <!--    <link rel="stylesheet" href="//cdn.jsdelivr.net/evil-icons/1.7.2/evil-icons.min.css">-->
    <!--    <script src="//cdn.jsdelivr.net/evil-icons/1.7.2/evil-icons.min.js"></script>-->
</head>
<body>

<div class="container">
    <nav class="navbar">
        <div class="container">
            <ul class="navbar-list">
                <li class="navbar-item">
                    <a href="<?php echo $this->config->environment->homepage; ?>" class="navbar-link">News Biu</a>
                </li>
                <!--                <li class="navbar-item">-->
                <!--                    <div data-icon="ei-bell" data-size="s"></div>-->
                <!--                </li>-->
                <li class="avatar">
                    <?php
                    $auth = $this->session->get('auth');
                    if (isset($auth)):
                        $name = $auth['name'];
                        $user = new User();
                        $u = $user->getUserByName($name);
                        ?>
                        <!--                        <div class="u-pull-right">-->
                        <!--                            <div data-icon="ei-bell" data-size="s"></div>-->
                        <!--                        </div>-->
                        <div class="u-pull-right">
                            <img src="<?php echo $u->avatarUrl;?>" class="profile-img"/>
                        </div>

                    <?php
                    endif;
                    ?>
                    <?php
                    if (!isset($auth)):
                        ?>
                        <a href="/member/login">
                            <div data-icon="ei-sc-github" data-size="m" class="login-button"></div>
                        </a>

                    <?php
                    endif;
                    ?>

                </li>
            </ul>
        </div>
    </nav>

    <?php echo $this->getContent(); ?>

    <!--    no whitespace !!-->
    <div>
        <div class="color-one-divider"></div><div class="color-two-divider"></div><div class="color-three-divider"></div><div class="color-four-divider"></div>
    </div>

    <div class="container">
        <div class="u-pull-left"><a href="/humans.txt">About</a></div>
        <div class="u-pull-right"><a href="">Report an issue</a></div>
    </div>

</div>

<!--<div>-->
<!--    <div class="color-one-divider"></div>-->
<!--    <div class="color-two-divider"></div>-->
<!--    <div class="color-three-divider"></div>-->
<!--    <div class="color-four-divider"></div>-->
<!--</div>-->

</body>
</html>